apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proyecto-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/cesarcanro1/proyecto-web:latest
          ports:
            - containerPort: 8080  # Spring Boot

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: proyecto-web
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: proyecto-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
    - host: backend.${NODE_IP}.nip.io   # ← se rellena al aplicar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
